name: Django CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          password: ${{ secrets.EC2_PASSWORD }}
          script: |
            cd /home/talentsprout/Freelance_Student_App/Student_project || exit 1

            echo " Updating server..."
            sudo apt-get update
            sudo apt-get install -y python3-venv

            echo " Creating/Activating virtual environment..."
            [ ! -d env ] && python3 -m venv env
            source env/bin/activate

            echo " Pulling latest code..."
            git pull origin main

            echo " Installing requirements..."
            pip install --upgrade pip
            pip install django-countries
            pip install -r requirements.txt

            echo " Applying migrations..."
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput

            echo " Restarting Gunicorn..."
            pkill gunicorn || true
            nohup gunicorn --workers 3 --bind unix:/tmp/gunicorn.sock Student_project.wsgi:application > gunicorn.log 2>&1 &

            echo " Fixing socket permissions..."
            sudo chown www-data:www-data /tmp/gunicorn.sock
            sudo chmod 660 /tmp/gunicorn.sock

            echo " Restarting Nginx..."
            sudo systemctl restart nginx
